# Configuração do Servidor Proxy Enterprise
enroll_secret = "seu-segredo-super-dificil"

[network]
enroll_port = ":8082"   # Porta de Matrícula (HTTPS)
tunnel_port = ":8081"   # Porta do Túnel (mTLS)
proxy_port  = ":8080"   # Porta de Uso (HTTP Proxy)
admin_port  = ":8083"   # Porta do Painel Web

[security]
admin_token = "supersecret12313131"  # Senha mestra do Dashboard